COPYING
README.md
include/secp256k1_frost.h
src/modules/frost/README.md
src/modules/frost/main_impl.h
src/modules/frost/tests_impl.h

This PR:
- adds a copyright header in the frost module, in line with what already exists - for example - for the `schnorrsig` module:
https://github.com/bitcoin-core/secp256k1/blob/5b32602295ff7ad9e1973f96b8ee8344b82f4af0/src/modules/schnorrsig/main_impl.h#L1-L5
This is the header that gets added:
```
/***********************************************************************
* Copyright (c) 2023 Bank of Italy                                    *
* Distributed under the MIT software license, see the accompanying    *
* file COPYING or https://www.opensource.org/licenses/mit-license.php.*
***********************************************************************/
```
- modifies the READMEs to mention that the original author of the Frost module is Bank of Italy.

doc: add copyright headers to Frost module

---

include/secp256k1_frost.h
src/modules/frost/main_impl.h
src/modules/frost/tests_impl.h

This commits adds two new functions secp256k1_frost_pubkey_save() and secp256k1_frost_pubkey_load(), which allows to save public keys within the secp256k1_frost_pubkey data struct. These functions are useful to export and import, respectively, such public keys.

FROST: add secp256k1_frost_pubkey_save() and load()

---

src/modules/frost/main_impl.h

The upstream function `secp256k1_ge_set_xo_var()` in `src/group_impl.h` returns an int signalling an error condition, but it is not marked with `SECP256K1_WARN_UNUSED_RESULT`.
Thus, when compiling the Frost module, no warning was generated when `deserialize_frost_signature()` did not check the return value of that function.
The gcc static analyzer found two potential execution paths in `secp256k1_frost_verify()` that would lead to undefined behaviour.
As of today (2023-05-29), in bitcoin-core secp256k1, secp256k1_ge_set_xo_var() is still not marked `SECP256K1_WARN_UNUSED_RESULT`, see: https://github.com/bitcoin-core/secp256k1/blob/908e02d596b66203788e8945b1f9c93ff28a4536/src/group_impl.h#L280. **It may make sense to propose upstream to add that annotation**.
In order to replicate the …

Missing error check in deserialize_frost_signature() could lead to UB in secp256k1_frost_verify()

---

src/modules/frost/main_impl.h

The leak presented if `compute_binding_factors()` failed. In that case the error reporting path would not deallocate the binding factors that were allocated just above.
Found with gcc 13.1 via:
```
./configure SECP_CFLAGS="-fanalyzer -fanalyzer-transitivity" --disable-tests --disable-exhaustive-tests --disable-benchmark --enable-experimental --enable-module-frost
```
The analyzer found 3 leaks at `main_impl.h:1403`, all of them solved by this change.
A simplified branch analysis of the first one was the following:
```
In file included from src/secp256k1.c:767:
src/modules/frost/main_impl.h: In function 'secp256k1_frost_aggregate':
src/modules/frost/main_impl.h:1454:1: warning: leak of 'binding_factors.binding_factors' [CWE-401] [-Wanalyzer-malloc-leak]
1454 | }
| ^ …
```

Remove potential memory leak in secp256k1_frost_aggregate()

---

src/modules/frost/main_impl.h

In this way we have a single way of clearing binding factors across the entire code base. Before this change, `secp256k1_frost_sign()` was the only function that rolled its own code.
This PR should not bring any functional changes.

secp256k1_frost_sign(): use free_binding_factors() instead of manually rolled code

---

src/modules/frost/main_impl.h
src/modules/frost/tests_impl.h

Initialize gej points as points to infinity, instead of using invalid values.

frost: initialize point as infinity instead of invalid

---

libsecp256k1.pc.in

A reference per the pkg-config sytax can be found in "man 5 pc", or online at https://man.freebsd.org/cgi/man.cgi?query=pc&sektion=5&n=1
```
EXAMPLES
An example .pc file:
prefix=/home/kaniini/pkg   # this defines a variable
exec_prefix=${prefix}      # defining another variable with a substitution
libdir=${exec_prefix}/lib
includedir=${prefix}/include
Name: libfoo                                  # human-readable name
Description: an example library called libfoo # human-readable description
Version: 1.0
URL: http://www.pkgconf.org
Requires: libbar > 2.0.0
Conflicts: libbaz <= 3.0.0
Libs: -L${libdir} -lfoo
Libs.private: -lm
Cflags: -I${includedir}/libfoo
```

Mention frost in the pkg-config description of the library. Link to Bank of Italy's github fork

---

src/modules/frost/main_impl.h

Given that - at least for now - we are allocating memory dynamically, let's free it as soon as it is no longer needed.
Valgrind shows no regressions.

In compute_binding_factor(), free encoded_group_commitments as soon as no longer needed

---

src/modules/frost/README.md

- fixed a typo;
- wrap function names in backticks (``);
- uniform use of punctuation at end of bulleted list items (removing it).

Fixes in frost/README.md

---

.github/workflows/functional-tests.yml

Configuration:
1. Without coverage:
```
./configure \
SECP_CFLAGS="-Werror" \
--enable-tests \
--disable-exhaustive-tests \
--disable-benchmark \
--disable-coverage \
--enable-experimental \
--enable-module-frost
```
2. With coverage `-Werror` has to be disabled:
```
./configure \
SECP_CFLAGS="" \
--enable-tests \
--disable-exhaustive-tests \
--disable-benchmark \
--enable-coverage \
--enable-experimental \
--enable-module-frost
```
GCC 13, fedora 38.

ci: run functional tests on frost module

---

.github/workflows/functional-tests.yml
README.md

The updated README after merging this PR can be seen at https://github.com/bancaditalia/secp256k1-frost/blob/add-badge/README.md.
Sample:

doc: add badge with the status of the last CI run on frost branch

---

.github/workflows/tests-and-examples-under-valgrind.yml

This CI workflow builds the minimum code necessary to run the Frost test suite and the Frost example, and runs them under Valgrind, exiting if it detects any problems.
The example is run first because it takes way less time.

ci: run Frost tests and example under Valgrind

---

.github/workflows/verify-version-consistency.yml
scripts/README.md
scripts/verify-version-consistency.sh

Our project version number is structured as following: `major.minor.patch-itcoin-frost-build` (for example: `0.3.0-frost-1`).
secp256k1 **v0.3.0** introduced support for building via CMake. In the process, it also duplicated the places where the version information is stored: no longer just `configure.ac`, but also `CMakeLists.txt`.
We now have to ensure that the two files are in sync. Additionally, we have to do the same check for the frost-specific version number.
The PR introduces a script that takes care of this and integrates the check in the CI.

ci: check version consistency between autotools and cmake

---

.github/workflows/build-with-cmake.yml
.github/workflows/functional-tests.yml
.github/workflows/tests-and-examples-under-valgrind.yml

Workflow `verify-version-consistency` was the last one written, and already used checkout@v4.
Let's align all the remaining workflows to use [the most recent action version](https://github.com/actions/checkout).
No functional changes.

ci: update "actions/checkout@v3" -> "actions/checkout@v4"

---

.github/workflows/build-with-cmake.yml
.github/workflows/functional-tests.yml
.github/workflows/tests-and-examples-under-valgrind.yml
.github/workflows/verify-version-consistency.yml

This should be a very low risk change, since the only CI job that directly uses the base image is [verify-version-consistency.yml](https://github.com/bancaditalia/secp256k1-frost/blob/838792f9bdc8c2bfc4efa55e6c5fa42dabc0c284/.github/workflows/verify-version-consistency.yml), which only depends on bash.
All the other workflows run in containers and should be unaffected; we will update the base image in the next PR.
List of installed software on the two platforms, in order to see the changes:
- https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
- https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md

ci: update runners (ubuntu 22.04 -> 24.04)

---

.github/workflows/build-with-cmake.yml
.github/workflows/functional-tests.yml
.github/workflows/tests-and-examples-under-valgrind.yml

ci: update base image "fedora:39" -> "fedora:41"

---

src/modules/frost/main_impl.h

Before returning, `secp256k1_frost_keygen_dkg_begin()` clears private data in order to reduce the risk of leaks.
This PR replaces `secp256k1_scalar_set_int()` with `secp256k1_scalar_clear()`. The effect is almost identical, but we use a centralized function, with a clear intent, and no additional free parameters.
Note for validating the change: the current implementation is in `src/scalar_low_impl.h` and is the following:
```
SECP256K1_INLINE static void secp256k1_scalar_clear(secp256k1_scalar *r) { *r = 0; }
```
In that same file, immediately below, there is the implementation of `secp256k1_scalar_set_int()`:
```
SECP256K1_INLINE static void secp256k1_scalar_set_int(secp256k1_scalar *r, unsigned int v) { *r = v; }
```
The performance-optimized overloads are in `src/scalar_4x64_impl.h` …

frost: use secp256k1_scalar_clear() in secp256k1_frost_keygen_dkg_begin()

---

src/modules/frost/main_impl.h

The opportunity for this change is more evident now that multiple variables are multiplied by the "special" value `secp256k1_scalar_one`.
Observing the calls, we notice that the variables were previously initialized to infinity via a call to `secp256k1_gej_set_infinity()`.
`secp256k1_gej_mul_scalar()` handles the special case by also setting infinity in the result. This would happen every time, hence we can remove the calls.

frost: remove redundant secp256k1_gej_mul_scalar() when the first factor is infinity

---

.github/workflows/tests-for-windows.yml

This PR adds a `tests-for-windows` workflow that builds a win64 version of the library with both autotools and CMake, and then attempts to run the frost example and the functional tests via wine.
In its current state, the builds fail because `getrandom()` does not exist under Windows.
The new workflow verifies that the Windows builds are failing, in order to offer a way of flipping the check when the Windows binaries will be working.

ci: build for Windows, and show that Windows builds are currently not supported

---

.github/workflows/tests-for-windows.yml
Makefile.am
src/CMakeLists.txt
src/modules/frost/fill_random.h
src/modules/frost/main_impl.h

This PR introduces support for windows builds, changing the design of `initialize_random_scalar()` and updating the build scripts.
1. ~~the first commit introduces a `tests-for-windows` CI workflow that builds a win64 version of the library via mingw and runs the resulting windows executables (`frost_example.exe` and `tests.exe`) via Wine.
In this first iteration, the build fails because frost uses `getrandom()`, which does not exist under windows.
The workflow enforces this failure;~~
2. the second commit replaces `getrandom()` with `BCryptGenRandom()` under windows, drawing from upstream's `examples/examples_util.h` which shows a cross-platform way of filling buffers with randomness.
The build is now cross-platform, and the workflow `tests-for-windows` workflow is flipped to enforce …

support windows builds

---

.github/workflows/check-frost-header.yml
scripts/ensure-frost-header-is-precompilable.sh

This PR introduces a simple script that triggers the current failure to precompile the frost header, due to a missing `uint32_t` symbol, and introduces a CI workflow that verifies the failure (in order to fix it afterwards).
The script uses a convoluted syntax (taken from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108732#c2) to trigger the header precompilation without actually writing anything to disk. The reason is that for header precompilation gcc 14.2 (2025-04-07), does not support `-o /dev/null`, because it wants to mmap the output file.
In order to be as strict as possible, we compile in both C and C++, because the headers for fixed length integers have different names in the two languages.
**EVIDENCE OF THE ERROR (C)**:
```
$ scripts/ensure-frost-header-is-precompilable.sh c …
```

frost: show that header precompilation would fail

---

.github/workflows/check-frost-header.yml
include/secp256k1_frost.h

#39 showed that the frost module's header could not be precompiled.
This PR fixes the error and updates the CI in order to ensure it never happens again.
Depending on the host language, we include the proper stdlib header for fixed size integers: `<stdint.h>` for C and `<cstdint>` for C++.

frost: fix header precompilation error

---

include/secp256k1_frost.h

Very minor oversights in the inline documentation for the frost module.
Fixed together with @matteonardelli.

docs: fix minor oversights

---

CMakeLists.txt
configure.ac

The version that need to go into itcoin-v25 is **v0.3.2-frost-1**, and is not based on the final version of secp256k1 (because bitcoin v25 did so).
This proposed version (**v0.3.2-frost-2**), instead, incorporates the final secp256k1 v0.3.2, and includes our recent changes: simplifications in the math performed in the frost module, multiplatform support and better CI checks.
These changes originated from the upgrading effort to v0.4.0 (#35), that we decided to apply to 0.3.2 _before_ upgrading the secp256k1 version.

Release v0.3.2-frost-2

---

.github/workflows/build-with-cmake.yml
.github/workflows/check-frost-header.yml
.github/workflows/functional-tests.yml
.github/workflows/tests-and-examples-under-valgrind.yml
.github/workflows/tests-for-windows.yml
examples/frost.c
examples/schnorr.c
src/modules/ellswift/tests_impl.h
src/modules/frost/main_impl.h
src/modules/frost/tests_impl.h
src/modules/schnorrsig/main_impl.h
src/modules/schnorrsig/tests_impl.h
src/testrand_impl.h

Let's bump the frost-specific CI toolchain to fedora 42, gcc 15.1.
Moreover, before this change `tests-for-windows.yml` had to dance around a bug in coreutils 9.5 (the support for `cp --update=none-fail` is broken there). Fedora 42 moves to coreutils 9.6 and we can revert back the hack.
The CI from upstream stays the same.

ci: update toolchain to Fedora 42 / GCC 15.1

---

.github/workflows/frost-build-with-cmake.yml
.github/workflows/frost-check-header.yml
.github/workflows/frost-functional-tests.yml
.github/workflows/frost-on-windows.yml
.github/workflows/frost-tests-and-examples-under-valgrind.yml
.github/workflows/frost-verify-version-consistency.yml

We are a fork: it makes sense to make easily distinguishable the contributions that do not come from upstream.
No functional changes.

ci: prefix with "frost-" all workflows not coming from upstream
